CREATE USER sustc_reader WITH PASSWORD '123456';
CREATE USER sustc_writer WITH PASSWORD '123456';

GRANT CONNECT ON DATABASE postgres TO sustc_reader;
GRANT CONNECT ON DATABASE postgres TO sustc_writer;

GRANT USAGE ON SCHEMA public TO sustc_reader;
GRANT USAGE ON SCHEMA public TO sustc_writer;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO sustc_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sustc_reader;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sustc_writer;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO sustc_writer;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sustc_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO sustc_writer;
